SELECT COU."YEAR", COL."MAJOR_NAME", COUNT(COU."COURSE_ID")
FROM 
"COURSE" AS COU, "COLLEGE" AS COL
WHERE COU."COURSE_ID_PREFIX" != 'XYZ' AND COU."COURSE_ID_PREFIX" = COL."MAJOR_ID"
GROUP BY COU."YEAR", COL."MAJOR_NAME"
ORDER BY COU."YEAR" ASC, COUNT(COU."COURSE_ID") DESC
